#!/bin/sh

cd ../template
# remove any user defined csl/tex files, and use sensible defults from git repos...
rm *.csl
rm *.tex

curl -o def.tex https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/eisvogel.tex

## Definitive Harvard style...
# curl -o def.csl https://raw.githubusercontent.com/citation-style-language/styles/master/harvard-cite-them-right.csl

## use the OU Harvard style instead...
curl -o def.csl https://raw.githubusercontent.com/citation-style-language/styles/master/the-open-university-harvard.csl
